// Bundle the agent into a single ESM file that runs on the Node shipped in the image.
import { build } from "esbuild";
import { mkdirSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "dist", "image");
mkdirSync(out, { recursive: true });

await build({
  entryPoints: [join(here, "..", "src", "main.ts")],
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  outfile: join(out, "agent.mjs"),
  banner: { js: "// sandbox-agent bundle (generated by image/build.mjs)" },
  logLevel: "warning",
});
await build({
  entryPoints: [join(here, "..", "src", "sudo-shim.ts")],
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  outfile: join(out, "sudo.mjs"),
  logLevel: "warning",
});
copyFileSync(join(here, "Dockerfile"), join(out, "Dockerfile"));
console.log(`image sources written to ${out}`);
